### PR TITLE
Unset the "reviewed" status of a file if its contents changed

### PR DESCRIPTION
**Pull request by DethAriel**
This is done by saving an md5 hash of the diff, and comparing the current hash with what is stored.

### CODE REVIEW

**Comment by DethAriel** [comment]
Here's a demo:

reviewed-checks-demo

**Comment by minhdam** [comment]
@DethAriel,
Perfect! Thanks for spending your time to implement it.
I will take some time to review and test your PR. If all good, I will merge it soon.
Cheers.

**Comment by DethAriel** [comment]
@minhdam are there any blockers/enhancements that you've spotted so far?

**Comment by minhdam** [comment]
@DethAriel It works perfectly. I just merged it into master. I will deploy a new version of the extension soon.

Very good work. Thank you, mate.

**Pull request merged**
